<div class="dashboardContainer">
            <div class="padding">
            <div class="dashboardMenuDiv">
            
            <div class="dashboardMenu">
            <ul>
            
            <li class="selected"><a href="<?php echo $this->url('dashboard'); ?>">Manage User Section</a></li>

           
            </ul>
            </div>
            
            </div>
             
            <div class="contentPanel">
			 <div class="dashboardIconFeatureDiv">
             <a href="<?php echo $this->url('admin/default', array('controller' => 'user', 'action' => 'subuser')); ?>"><div class="dashboardReportsIcon"></div>
             <div class="dashboardCommonTxtDiv"> Manage Sub User
</div></a>
 
            </div>
    		 <div class="dashboardIconFeatureDiv">
             <div class="dashboardVehiclMaintainanceIcon"></div>
             <div class="dashboardCommonTxtDiv"> Vehicle Maintainance
</div>
 
            </div>           
             <div class="dashboardIconFeatureDiv">
             <div class="dashboardManageTariffIcon"></div>
             <div class="dashboardCommonTxtDiv"> Manage Tariff
</div>
 
            </div>
             <div class="dashboardIconFeatureDiv">
             <div class="dashboardManageBookingIcon"></div>
             <div class="dashboardCommonTxtDiv"> Manage Bookings
</div>
 
            </div>
             <div class="dashboardIconFeatureDiv">
             <div class="dashboardSalesnMktIcon"></div>
             <div class="dashboardCommonTxtDiv"> Sales &amp; Marketing
</div>
 
            </div>
             <div class="dashboardIconFeatureDiv">
             <div class="dashboardHRMIcon"></div>
             <div class="dashboardCommonTxtDiv"> Human Resource Management
</div>
 
            </div>
             <div class="dashboardIconFeatureDiv">
             <div class="dashboardManageUserIcon"></div>
             <div class="dashboardCommonTxtDiv"> Manage User
</div>
 
            </div>
             <div class="dashboardIconFeatureDiv">
             <div class="dashboardManageAssetIcon"></div>
             <div class="dashboardCommonTxtDiv"> Assets Management
</div>
 
            </div>
            </div>
            </div>
</div>