<?php
$this->headTitle('Edit Bank');
?>
<div class="contentPanel">
    <div class="row ">
    <div class="col-sm-6 pull-left">
                <header>
                <h3 class="orange">EDIT BANK</h3>
                </header>
   </div>
   <div class="col-sm-6 pull-right"> 
   </div>
                
    </div>
<div class="addUserTitleStrip">
    <h4>EDIT BANK INFORMATION</h4>
   </div>
 <?php
             $form = $this->form;
//                $form->setAttribute(
//                     'action', $this->url('admin', 
//                array(
//                    'action'=>'bankedit',
//                    'id'=>$this->id,
//                          ))
//                     );
                $form->prepare();
                echo $this->form()->openTag($form);
 ?>
    <div class="commonFormDtlsDiv">
        <?php echo $this->formRow($form->get('bankName'));?>
  </div>
<div class="btnCommonDiv">
        <?php echo $this->formInput($form->get('save'));?>
</div>
<?php
echo $this->form()->closeTag($form);
?>
</div>

