<?php $fieldcounts = count($this->fildnames) + 1; ?>
<div class="contentPanel">

    <div class="zf-table-wrap  form-inline">

        <div class="row ">
            <div class="col-sm-6 pull-left">
                <header>
                    <h3 class="orange">MANAGE SUB USER</h3>
                </header>
            </div>
            <div class="col-sm-6 pull-right"> 
                <div class="addUserBtn"><a href="<?php echo $this->url('admin/default', array('controller' => 'user', 'action' => 'subuseradd')); ?>">ADD SUB USER</a></div>
            </div>

        </div>
        <div class="addUserTitleStrip">
            <h4>SUB USER LIST</h4>
        </div>

    </div>
    <div id="tableContainer">
        <table id="subuser" class="display table table-striped table-bordered" cellspacing="0" width="100%">
            <thead>
                <tr class="dataTable-title">
                    <th>Sr. No</th>
                    <?php
                    for ($j = 0; count($fildnames) > $j; $j++) {
                        $fieldnameval = $fildnames[$j];
                        echo "<th>$fieldnameval</th>";
                    }
                    ?>
    <!--                <th>Action</th>-->
                    <th>Action
                    </th>
                </tr>
            </thead>



        </table>
    </div>

</div> 
<script type="text/javascript">
    $(document).ready(function () {
        var t = $('#subuser').DataTable({
            stateSave: true,
            responsive: true,
            dom: 'C<"clear">lfrtip',
            colVis: {
                activate: "mouseover",
                exclude: [0, 1,<?php echo $fieldcounts; ?>]
            },
            "ajax": {
                "url": "/admin/user/ajaxsubuser",
                "dataSrc": "data"
            },
            "columnDefs": [{
                    "targets": -1,
                    "data": null,
                    "render": function (data, type, full, meta) {
                        var dataval = "/admin/user/subuseredit/" + data[1];
                        return '<span class="userEditOptionsDiv"><span class="userEditOptionsPopup"><span class="userEditOptionTxt"><a href="' + dataval + '">Modify Sub User</a></span><span class="userEditOptionTxt status"  id="' + data[1] + '"><a  href="javascript:void(0)" >Change Status</a></span></span></span>';
                    },
                    // "defaultContent": '<span class="userEditOptionsDiv"><span class="userEditOptionsPopup"><span class="userEditOptionTxt"><a href="">Modify Sub User</a></span><span class="userEditOptionTxt status"  id="%s"><a  href="javascript:void(0)" >Change Status</a></span></span></span>',
                    "orderable": false
                }, {
                    "targets": [1],
                    "visible": false
                }, {
                    "searchable": false,
                    "orderable": false,
                    "targets": 0
                }],
            "order": [[1, 'asc']]

        });
        t.on('order.dt search.dt', function () {
            t.column(0, {search: 'applied', order: 'applied'}).nodes().each(function (cell, i) {
                cell.innerHTML = i + 1;
            });
        }).draw();
         t.on('order.dt search.dt', function () {
            $(".userEditOptionsDiv").hover(function () {
                $(this).children('.userEditOptionsPopup').show();
            }, function () {
                $(this).children('.userEditOptionsPopup').hide();
            });
        }).draw();
    });

</script>   

<!--// $("#tableContainer").zfTable('/admin/user/ajax-subuser');-->




