<?php
echo $this->doctype();
?>
<?php date_default_timezone_set("Asia/Kolkata"); ?>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle('CabSaaS ' . $this->translate('Inventory and Fleet Management '))->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php
        echo $this->headMeta()
                ->appendName('viewport', 'width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no')
                ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?php
        echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/ico', 'href' => $this->basePath() . '/images/favicon.ico'))
                ->prependStylesheet($this->basePath('css/bootstrap.css'))
                ->prependStylesheet($this->basePath('css/cabsaas-style.css'))
                ->prependStylesheet($this->basePath('css/datatables/jquery.dataTables.css'))
                ->prependStylesheet($this->basePath('css/datatables/dataTables.colVis.css'))
        // ->prependStylesheet($this->basePath('css/dataTables.bootstrap.css'))
//                 ->prependStylesheet($this->basePath() . '/admin/styles/font-awesome.min.css')
//                ->prependStylesheet($this->basePath() . '/admin/styles/all.css')
//                ->prependStylesheet($this->basePath() . '/admin/styles/main.css')
        //date js
        ?>
        <!-- Scripts -->
        <?php
        echo $this->headScript()
                ->prependFile($this->basePath('js/ie-emulation-modes-warning.js'))
                ->prependFile($this->basePath('js/jquery-2.1.3.min.js'))
        ;
        ?>

    </head>
    <body>

        <div class="adminTopHeader">        <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed menuToggleTopMargin" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>

                <div class="dashboardUserCompanyLogoDiv">
                    <div class="dashboardUserCompanyLogo"><img src="/images/logo/cabsaas.png" alt="cabsaas" class="img-circle"></div>
                    <div class="dashboardUserCompanyName">
                        Cabsaas Pvt. Ltd.
                    </div>
                </div> 


            </div>
            <div id="navbar" class="navbar-collapse collapse">
                <!--        <form class="dashboard-InputOuterDiv">
                            <input type="text" class="dashboard-SearchDiv" placeholder="">
                          </form>-->
                <div class="topHdrNotificationsContains">

                    <div class="dashboardTopHdrCommonDiv"><div class="msgIconDiv"><span class="notificationBox">1</span></div></div>
                    <div class="dashboardTopHdrCommonDiv"><div class="notificationIconDiv"><span class="notificationBox">1</span></div></div>
                    <div class="dashboardTopHdrCommonDiv"> 
                        <div class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><?php echo $this->escapeHtml(ucfirst($this->user->firstName)) . " " . $this->escapeHtml(ucfirst($this->user->lastName)); ?> <span class="caret"></span></a>
                            <ul class="dropdown-menu">
                                <li><a href="#">My Profile</a></li>

                                <li role="separator" class="divider"></li>
                                <li><a href="#">My Settings</a></li>
                                <li role="separator" class="divider"></li>
                                <li><a  href="<?php echo $this->url('signin', array('action' => 'logout')); ?>" >Log Out</a></li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </div> 




        <div style="width:100%; height:auto; float:left; position:relative; overflow-y:hidden; background:#f1f1f1;  "><div class="adminLeftPanel">
                <div class="vBar">
                    <div class="vInner">
                        <ul id="accordion" class="accordion">
                            <li>
                                <div class="link"><a href="<?php echo $this->url('admin/default', array('controller' => 'user', 'action' => 'userdashboard')); ?>"> <i class="userIcon"></i>USER</a> </div>
                            </li>
                            <li>
                                <div class="link"><a href="<?php echo $this->url('vehicle'); ?>"><i class="vehicleIcon"></i>VEHICLE</a></div>

                            </li>
                            <li>
                                <div class="link"><a href="<?php echo $this->url('tariff/default', array('controller' => 'roundtrip', 'action' => 'view')); ?>"><i class="tariffIcon"></i>TARIFF</a></div>

                            </li>
                            <li>
                                <div class="link"><a href="<?php echo $this->url('vehicle'); ?>"><i class="bookingIcon"></i>BOOKINGS</a></div>
                            </li>
                            <li>
                                <div class="link"><a href="<?php echo $this->url('vehicle'); ?>"><i class="cityLocationIcon"></i>CITY &amp; LOCATION</a></div>
                            </li>

                            <li>
                                <div class="link"><a href="<?php echo $this->url('vehicle'); ?>"><i class="AcFinanceIcon"></i>ACCOUNT &amp; FINANCE</a></div>
                            </li>
                            <li>
                                <div class="link"><i class="reportAnaIcon"></i>REPORTS<i class="fa fa-chevron-down"></i></div>
                            </li>
                            <li>
                                <div class="link"><i class="plansIcon"></i>PLANS<i class="fa fa-chevron-down"></i></div>
                                <!--    <ul class="submenu">
                                      <li><a href="#">Google</a></li>
                                      <li><a href="#">Bing</a></li>
                                      <li><a href="#">Yahoo</a></li>
                                    </ul>-->
                            </li>
                            <li>
                                <div class="link"><i class="assetMgmtsIcon"></i>ASSET MANAGEMENT<i class="fa fa-chevron-down"></i></div>
                            </li>
                            <li>
                                <div class="link"><i class="salesMrkIcon"></i>SALES &amp; MARKETING<i class="fa fa-chevron-down"></i></div>
                            </li>
                            <li>
                                <div class="link"><i class="HRMrkIcon"></i>HR MANAGEMENT<i class="fa fa-chevron-down"></i></div>
                            </li>
                            <li>
                                <div class="link"><i class="QCIcon"></i>QUALITY CONTROL<i class="fa fa-chevron-down"></i></div>
                            </li>
                            <li>
                                <div class="link"><i class="websiteMgmIcon"></i>USER WEBSITE MANAGEMENT<i class="fa fa-chevron-down"></i></div>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>

            <div class="adminRightBigPanel"> 
                <?php echo $this->content; ?>
            </div>

        </div>      
        <div class="footerFinal">
            <div class="footerDiv">
                &copy; 2011 - <?php echo date('Y') ?> CabSaaS. &middot; All Right Reserved&nbsp;&nbsp;&nbsp;&nbsp;  <a href="#">Privacy Policy</a>&nbsp;&nbsp;   &middot; &nbsp;&nbsp;  <a href="#">Terms &amp; Conditions</a>&nbsp;&nbsp; &middot;&nbsp;&nbsp;   <a href="#">Help</a>&nbsp;&nbsp;  &middot; &nbsp;&nbsp;  <a href="#">Contact Us</a>
            </div>
        </div>

        

        <style>

            .userEditOptionsPopup{
              display:none;
               //z-index: 10;
            }
        </style>
          
        <script>
            $(".vInner").hover(function () {
                $('.vBar').animate({width: "250"}, 200);
            }, function () {
                $('.vBar').animate({width: "60"}, 200);
            });
        </script>
        <script>
//            $(function () {
//                var Accordion = function (el, multiple) {
//                    this.el = el || {};
//                    this.multiple = multiple || false;
//
//                    // Variables privadas
//                    var links = this.el.find('.link');
//                    // Evento
//                    links.on('click', {el: this.el, multiple: this.multiple}, this.dropdown)
//                }
//
//                Accordion.prototype.dropdown = function (e) {
//                    var $el = e.data.el;
//                    $this = $(this),
//                            $next = $this.next();
//
//                    $next.slideToggle();
//                    $this.parent().toggleClass('open');
//
//                    if (!e.data.multiple) {
//                        $el.find('.submenu').not($next).slideUp().parent().removeClass('open');
//                    }
//                    ;
//                }
//
//                var accordion = new Accordion($('#accordion'), false);
//            });
        </script>  
     
        <?php
        echo $this->inlineScript()
                ->prependFile($this->basePath('js/ie10-viewport-bug-workaround.js'))
                //  ->prependFile(https://code.jquery.com/jquery-2.1.3.min.js))
                //->prependFile($this->basePath('js/date/jquery-ui.js'))
                ->prependFile($this->basePath('js/bootstrap.min.js'))
                //->prependFile($this->basePath('js/dataTables/dataTables.colVis.js'))
         //->prependFile($this->basePath('js/datatables/jquery-1.11.1.min.js'))
        // ->prependFile($this->basePath('js/datatables/jquery.dataTables.min.js'))
         //        ->prependFile($this->basePath('js/datatables/dataTables.bootstrap.js'))
        // ->prependFile($this->basePath('js/datatables/dataTables.colVis.js'))
        ?>
 <script src="/js/datatables/jquery-1.11.1.min.js"></script>
        <script src="/js/datatables/jquery.dataTables.min.js"></script>
        <script src="/js/datatables/dataTables.bootstrap.js"></script>
        <script src="/js/datatables/dataTables.colVis.js"></script>

    </body>
</html>
