<?php
$this->headTitle('Edit city category');
?>
<div class="contentPanel">
    <div class="row ">
    <div class="col-sm-6 pull-left">
                <header>
                  <h3 class="orange">ADD CITY CATEGORY</h3>
                </header>
   </div>
   <div class="col-sm-6 pull-right"> 
   </div>
                
    </div>
<div class="addUserTitleStrip">
    <h4>EDIT CITY CATEGORY INFORMATION</h4>
   
    </div>
 <?php
              $form = $this->form;
              $form->prepare();
              echo $this->form()->openTag($form);
              
 ?>
    <div class="commonFormDtlsDiv">
        
<?php echo $this->formRow($form->get('ctCatName'));?>
        </div>
    
    <div class="commonFormDtlsDiv">

<?php echo $this->formRow($form->get('ctCatInfo'));?>
        </div>
 
     <div class="btnCommonDiv">
<?php echo $this->formInput($form->get('save'));?>
</div>
        
<?php
echo $this->form()->closeTag($form);
?>
 
  </div>

