<?php
$this->headTitle('STATE');
?>
<div class="contentPanel">
    <div class="row ">
    <div class="col-sm-6 pull-left">
                <header>
                <h3 class="orange">ADD NEW STATE</h3>
                </header>
   </div>
   <div class="col-sm-6 pull-right"> 
   </div>
                
    </div>
<div class="addUserTitleStrip">
    <h4>STATE INFORMATION</h4>
  
    </div>
 <?php
                $form = $this->form;
                $form->prepare();
                echo $this->form()->openTag($form);
 ?>
    <div class="commonFormDtlsDiv">
    <div class="commonDropDnInput">
<?php echo $this->formSelect($form->get('cntryId')) ;?>
    </div></div>
    <div class="commonFormDtlsDiv">
     <?php echo $this->formElementErrors($form->get('cntryId')); ?>

    </div>
   
    
    <div class="commonFormDtlsDiv">
            <?php echo $this->formRow($form->get('stname'));?>
        </div>
    <div class="commonFormDtlsDiv">
            <?php echo $this->formRow($form->get('statedescription'));?>
        </div>
    
     <div class="commonFormDtlsDiv">
            <?php echo $this->formRow($form->get('statespecialInstructions'));?>
        </div>
    
     <div class="commonFormDtlsDiv">
     <?php echo $this->formRow($form->get('statebestSeasonToVisit'));?>
        </div>
    
   
    
    <div class="commonFormDtlsDiv">

<?php echo $this->formRow($form->get('latitude'));?>
        </div>
    
    <div class="commonFormDtlsDiv">

<?php echo $this->formRow($form->get('longitude'));?>
        </div>
    
  
     <div class="commonFormDtlsDiv">

<?php echo $this->formRow($form->get('statePhoto'));?>
        </div>  
    
    
     <div class="btnCommonDiv">
<?php echo $this->formInput($form->get('save'));?>
</div>
        
<?php
echo $this->form()->closeTag($form);
?>
 
  </div>

